# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6309eed12550bef1b044036c20cd202e79f52ff9b187767ef96514b848c41cff7fbc16ab541df7c751ec9eea48b18b89d93cfc0f9449cfd3f7ff48b3521552e

test:
  secret_key_base: daa3b79c80d3cd43cf7bd6b1ae5eaa278af65379c1f126af9570825293d5cfb05beb90838ce22ef6fbd2ed84dfaf608a73a72d5e6c1c34ca74dac377b17d7f0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
